[workspace]
authors = ["sophia <scastellarin@openteams.com>"]
channels = ["conda-forge"]
name = "whats-my-team-up-to"
platforms = ["linux-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks]
find-my-team = { description = "Populate the team.txt list with github usernames associated with OpenTeams", cmd = ["gh", "api", "--paginate", "/orgs/openteams-ai/members", "--jq", ".[].login", ">", "team.txt"] }
collect-prs = { description = "Collect PRs from the team members and save to a JSON file", cmd = ["python", "scripts/collect_prs.py", "--team-file", "team.txt", "--output", "prs.json"] }

[dependencies]
python = ">=3.10,<3.15"
gh = ">=2.92.0,<3"
requests = ">=2.33.1,<3"
